#!/usr/bin/env bash
#

#A script to show current power profile

current_profile=$(/usr/bin/powerprofilesctl get)
if [ $current_profile = "power-saver" ]
then 
  echo ""
elif [ $current_profile = "performance" ]
then
  echo ""
else
  echo "𢡄"
fi


